import {test,expect} from "@playwright/test";
import type {Page} from "../lib/types";

test("live news browsing, attribution, categories and pagination", async ({page,request},testInfo)=>{
  const health=await (await request.get("/api/v1/health")).json();
  test.skip(health.demo_mode,"Live suite requires DEMO_MODE=false and a completed ingestion.");
  const errors:string[]=[];
  page.on("pageerror",error=>errors.push(error.message));
  const data:Page=await (await request.get("/api/v1/articles?page_size=9")).json();
  expect(data.total).toBeGreaterThan(16);
  expect(data.items.every(article=>!article.demo)).toBeTruthy();
  await page.goto("/");
  await expect(page.locator(".lead-story")).toBeVisible();
  await expect(page.getByText("Demo edition",{exact:true})).toHaveCount(0);
  await expect(page.locator(".lead-story h2")).toHaveText(data.items[0].headline);
  await expect(page.locator(".lead-story img")).toBeVisible();
  await page.locator(".lead-story img").evaluate((image:HTMLImageElement)=>image.decode());
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
  await page.screenshot({path:`../test-results/${testInfo.project.name}-live-light.png`,fullPage:true});
  await page.getByRole("button",{name:/Theme: system/}).click();
  await expect(page.locator("html")).toHaveAttribute("data-theme","dark");
  await page.screenshot({path:`../test-results/${testInfo.project.name}-live-dark.png`,fullPage:true});
  await page.getByRole("link",{name:"Read the story",exact:true}).click();
  await expect(page).toHaveURL(/\/article\//);
  const original=page.getByRole("link",{name:"Read original article"});
  await expect(original).toHaveAttribute("href",data.items[0].original_url);
  await expect(page.locator(".detail-byline")).toContainText(data.items[0].source);
  await page.goto("/category/tamilnadu");
  await expect(page.locator(".article-grid .article-card").first()).toBeVisible();
  await page.goto("/search");
  await expect(page.getByRole("heading",{name:`${data.total} stories found.`})).toBeVisible();
  await page.getByRole("button",{name:"Next",exact:true}).click();
  await expect(page).toHaveURL(/page=2/);
  await expect(page.locator(".pagination")).toContainText("Page 2");
  await page.getByRole("combobox",{name:"Source",exact:true}).selectOption("NDTV.com");
  await expect(page.locator(".article-grid .article-card").first()).toBeVisible();
  await expect(page.locator(".article-grid .article-card").first()).toContainText("NDTV.com");
  expect(errors).toEqual([]);
});
